export const SUPPORTED_LANGUAGES = {
  en: { name: 'English', flag: '🇺🇸' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  pt: { name: 'Português', flag: '🇧🇷' },
  ru: { name: 'Русский', flag: '🇷🇺' },
  zh: { name: '中文', flag: '🇨🇳' },
  ja: { name: '日本語', flag: '🇯🇵' },
  ko: { name: '한국어', flag: '🇰🇷' },
  ar: { name: 'العربية', flag: '🇸🇦' },
  hi: { name: 'हिंदी', flag: '🇮🇳' },
  bn: { name: 'বাংলা', flag: '🇧🇩' },
  ur: { name: 'اردو', flag: '🇵🇰' },
  sw: { name: 'Kiswahili', flag: '🇰🇪' },
  am: { name: 'አማርኛ', flag: '🇪🇹' },
  yo: { name: 'Yorùbá', flag: '🇳🇬' },
  ha: { name: 'Hausa', flag: '🇳🇬' },
  ig: { name: 'Igbo', flag: '🇳🇬' },
  th: { name: 'ไทย', flag: '🇹🇭' },
  vi: { name: 'Tiếng Việt', flag: '🇻🇳' },
  id: { name: 'Bahasa Indonesia', flag: '🇮🇩' },
};

export const COUNTRIES = {
  US: 'United States',
  BR: 'Brazil',
  IN: 'India',
  KE: 'Kenya',
  NG: 'Nigeria',
  ET: 'Ethiopia',
  SA: 'Saudi Arabia',
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  DE: 'Germany',
  FR: 'France',
  ES: 'Spain',
  IT: 'Italy',
  RU: 'Russia',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  TH: 'Thailand',
  VN: 'Vietnam',
  ID: 'Indonesia',
};

export const SCHEME_CATEGORIES = {
  education: { icon: '🎓', color: 'bg-blue-500' },
  farmers: { icon: '🌾', color: 'bg-green-500' },
  business: { icon: '💼', color: 'bg-purple-500' },
  women: { icon: '👩', color: 'bg-pink-500' },
  housing: { icon: '🏠', color: 'bg-orange-500' },
  health: { icon: '🏥', color: 'bg-red-500' },
  employment: { icon: '💼', color: 'bg-indigo-500' },
  disability: { icon: '♿', color: 'bg-teal-500' },
  elderly: { icon: '👴', color: 'bg-gray-500' },
  youth: { icon: '👦', color: 'bg-yellow-500' },
};